name: 'Zig Cross-Compiler'
description: 'Cross-compilation for C, C++, Rust, and Go using Zig (no Docker required).'
inputs:
  version:
    description: 'Zig version to install'
    required: false
    default: '0.13.0'
  target:
    description: 'Target architecture (e.g., linux-arm64, x86_64-linux-gnu)'
    required: true
  project-type:
    description: 'Language preset (auto, go, rust, c, custom)'
    required: false
    default: 'auto'
  rust-musl-mode:
    description: 'Policy for Rust+Musl targets: deny (fail), warn (log), allow (silent-ish)'
    required: false
    default: 'deny'
  verify-level:
    description: 'Post-build verification: none | basic'
    required: false
    default: 'basic'
  cmd:
    description: 'Build command to execute'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Zig Cross-Compiler Environment
      shell: bash
      env:
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_PROJECT_TYPE: ${{ inputs.project-type }}
        INPUT_RUST_MUSL_MODE: ${{ inputs.rust-musl-mode }}
      run: |
        # Resolve script path relative to action location
        SCRIPT_PATH="${GITHUB_ACTION_PATH}/setup-env.sh"
        source "$SCRIPT_PATH"

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ inputs.version }}
        cache: false

    - name: Execute Build Command
      shell: bash
      run: |
        echo "Running cross-compilation for ${{ inputs.target }}..."
        ${{ inputs.cmd }}

    - name: Verify Output (Optional)
      shell: bash
      if: success() && runner.os != 'Windows' && inputs.verify-level != 'none'
      run: |
        echo "Checking for output artifacts..."
        # Heuristic to find binary
        find . -maxdepth 3 -type f -not -path '*/.*' -exec file {} \; | grep -i "ELF\|Mach-O\|PE32" || echo "No obvious binaries found to verify."
